// Auto-derived catalog seed data from reference/matlist-prototype.jsx (the
// agreed UX reference). 14 material families (CATS) + 29 fully-detailed
// materials. Regenerate by re-extracting the MAT array from the prototype.

// Thai category families, indexed to match each material's `cat` field.
export const CATEGORIES: { key: string; en: string }[] = [
  { key: "กระเบื้อง & พอร์ซเลน", en: "Tiles & Porcelain" },
  { key: "หินธรรมชาติ & หินขัด", en: "Stone & Terrazzo" },
  { key: "ไม้จริง & ไม้เอนจิเนียร์", en: "Wood & Engineered" },
  { key: "ไวนิล SPC & ลามิเนต", en: "Vinyl SPC & Laminate" },
  { key: "อิฐ & บล็อก", en: "Brick & Block" },
  { key: "ปูน คอนกรีต & ไฟเบอร์ซีเมนต์", en: "Concrete & Fiber Cement" },
  { key: "ยิปซัม & อะคูสติก", en: "Gypsum & Acoustic" },
  { key: "โลหะ & เหล็ก", en: "Metal & Steel" },
  { key: "กระจก & อะคริลิก", en: "Glass & Acrylic" },
  { key: "สี & สารเคลือบผิว", en: "Paint & Coatings" },
  { key: "ฉนวน & กันความร้อน", en: "Insulation" },
  { key: "ผ้า หนัง & วัสดุบุผิว", en: "Fabric & Upholstery" },
  { key: "สุขภัณฑ์ & ฟิตติ้ง", en: "Sanitary & Fittings" },
  { key: "แสงสว่าง & โคมไฟ", en: "Lighting" },
];

export interface RawMaterial {
  cat: number;
  brand: string;
  seller: string;
  model: string;
  th: string;
  en: string;
  unit: string;
  base: number;
  spec: string;
  specEn: string;
  cert: string;
  lead: string;
  wty: string;
  moq: string;
  note: string;
  noteEn: string;
  colors: string[][];
  sizes: string[];
}

export const RAW_MATERIALS: RawMaterial[] = [
  { cat: 0, brand: "COTTO", seller: "Grand Ceramics", model: "Arctic", th: "กระเบื้องพอร์ซเลน", en: "Porcelain tile", unit: "ตร.ม.", base: 890, spec: "ดูดซึมน้ำ <0.5% · Matt R9", specEn: "Water abs. <0.5% · Matt R9", cert: "มอก. 2508", lead: "7 วัน", wty: "10 ปี", moq: "20 ตร.ม.", note: "แนะนำยาแนวสีเดียวกับกระเบื้อง เว้นร่อง 2 มม.", noteEn: "Use matching grout, 2 mm joint", colors: [["ขาวหินอ่อน", "#E4E1DC"], ["เทาคาร์รารา", "#C9CBCE"], ["ดำแกรนิต", "#5A5B5E"], ["เบจทราเวอทีน", "#D8CBB4"]], sizes: ["60×60 ซม.", "60×120 ซม."] },
  { cat: 0, brand: "Duragres", seller: "Grand Ceramics", model: "Mist", th: "กระเบื้องผนัง", en: "Wall tile", unit: "ตร.ม.", base: 420, spec: "กันลื่น R11 · เหมาะงานเปียก", specEn: "Anti-slip R11 · wet areas", cert: "มอก. 2508", lead: "5 วัน", wty: "5 ปี", moq: "15 ตร.ม.", note: "รุ่นนี้มีขอบ rectified ปูชิดได้", noteEn: "Rectified edge, tight joints OK", colors: [["ขาวด้าน", "#EDEBE6"], ["เขียวเซจ", "#AEBFAE"], ["ฟ้าหมอก", "#AFC4CE"]], sizes: ["30×60 ซม."] },
  { cat: 0, brand: "EcoTile", seller: "EcoTile Studio", model: "Mosaic Glass", th: "โมเสกแก้วรีไซเคิล", en: "Recycled glass mosaic", unit: "ตร.ม.", base: 1180, spec: "แผ่นตาข่าย 30×30 · ทนคลอรีน", specEn: "Mesh 30×30 · chlorine-proof", cert: "—", lead: "12 วัน", wty: "5 ปี", moq: "5 ตร.ม.", note: "สั่งสีพิเศษได้ ขั้นต่ำ 50 ตร.ม.", noteEn: "Custom colors from 50 m²", colors: [["เขียวทะเล", "#7FB8AE"], ["น้ำเงินลึก", "#4A6A9C"], ["ทองชา", "#C0A060"]], sizes: ["2×2 ซม."] },
  { cat: 1, brand: "Siam Terrazzo", seller: "Siam Terrazzo Co.", model: "Classic Lime", th: "หินขัดเทอราซโซ", en: "Terrazzo", unit: "ตร.ม.", base: 1450, spec: "หนา 20 มม. · กันลื่น R10 · Recycled 30%", specEn: "20 mm · R10 · 30% recycled", cert: "มอก. 826", lead: "21 วัน", wty: "10 ปี", moq: "30 ตร.ม.", note: "หล่อหน้างานได้ ไร้รอยต่อ", noteEn: "Cast-in-place, seamless", colors: [["ครีมปูนขาว", "#C9C2B4"], ["เทาควันบุหรี่", "#A8A8A4"], ["ชมพูพาสเทล", "#D4B8B0"], ["เขียวหยก", "#9CB0A0"]], sizes: ["หล่อในที่", "แผ่น 60×60"] },
  { cat: 1, brand: "Stonefield", seller: "Stonefield TH", model: "Granite Flame", th: "หินแกรนิตเผาไฟ", en: "Flamed granite", unit: "ตร.ม.", base: 1850, spec: "หนา 30 มม. · ผิวเผาไฟกันลื่น", specEn: "30 mm · flamed anti-slip", cert: "—", lead: "14 วัน", wty: "—", moq: "10 ตร.ม.", note: "งานภายนอกควรเคลือบกันคราบ", noteEn: "Seal for exterior use", colors: [["ดำอินเดีย", "#4A4A4C"], ["เทาเขา", "#8A8C8A"]], sizes: ["30×60 ซม.", "60×60 ซม."] },
  { cat: 2, brand: "Woodwork", seller: "Woodwork Studio TH", model: "Oak Tri-layer", th: "ไม้เอ็นจิเนียร์โอ๊ค", en: "Engineered oak", unit: "ตร.ม.", base: 2190, spec: "หนา 15 มม. · ผิว UV Lacquer · E1", specEn: "15 mm · UV lacquer · E1", cert: "FSC", lead: "30 วัน", wty: "15 ปี", moq: "20 ตร.ม.", note: "ปรับสภาพไม้ในไซต์ 72 ชม. ก่อนติดตั้ง", noteEn: "Acclimatize on site 72 h", colors: [["โอ๊คธรรมชาติ", "#A9743F"], ["โอ๊ครมควัน", "#7A5230"], ["โอ๊คขาวแซนด์", "#C8A87C"]], sizes: ["190×1900 มม.", "220×2200 มม."] },
  { cat: 2, brand: "Northern", seller: "Northern Timber", model: "Teak Solid", th: "ไม้สักแท้", en: "Solid teak", unit: "ตร.ม.", base: 3400, spec: "หนา 18 มม. · อบแห้ง KD", specEn: "18 mm · kiln dried", cert: "FSC", lead: "45 วัน", wty: "—", moq: "10 ตร.ม.", note: "สีไม้เข้มขึ้นตามอายุ เป็นธรรมชาติของสัก", noteEn: "Natural darkening over time", colors: [["สักทอง", "#B08048"]], sizes: ["90×900 มม.", "120×1200 มม."] },
  { cat: 3, brand: "FloorMaster", seller: "FloorMaster", model: "AquaLock", th: "พื้น SPC คลิกล็อก", en: "SPC click-lock", unit: "ตร.ม.", base: 620, spec: "หนา 5 มม. · Wear 0.5 มม. · กันน้ำ 100%", specEn: "5 mm · wear 0.5 · waterproof", cert: "FloorScore", lead: "3 วัน", wty: "10 ปี", moq: "10 ตร.ม.", note: "ปูทับกระเบื้องเดิมได้ ถ้าพื้นเรียบ ±2 มม.", noteEn: "Install over tile if flat ±2 mm", colors: [["ไม้โอ๊คอ่อน", "#B8916A"], ["ไม้วอลนัท", "#7A5A42"], ["ไม้แอชเทา", "#A0968C"], ["หินเทา", "#9AA0A4"]], sizes: ["180×1220 มม."] },
  { cat: 3, brand: "VinylPro", seller: "VinylPro Asia", model: "Loose-lay", th: "กระเบื้องยาง LVT", en: "LVT loose-lay", unit: "ตร.ม.", base: 480, spec: "หนา 5 มม. · ถอดเปลี่ยนรายแผ่น", specEn: "5 mm · replace per plank", cert: "FloorScore", lead: "5 วัน", wty: "7 ปี", moq: "20 ตร.ม.", note: "เหมาะงานเช่า/รีโนเวต รื้อไม่ทิ้งร่องรอย", noteEn: "Great for rentals, no residue", colors: [["โอ๊คน้ำผึ้ง", "#B78B5C"], ["คอนกรีต", "#A8A8A6"]], sizes: ["500×500 มม.", "180×1220 มม."] },
  { cat: 4, brand: "บ้านโป่ง", seller: "โรงอิฐบ้านโป่ง", model: "เผาฟืนดั้งเดิม", th: "อิฐดินเผามือ", en: "Handmade clay brick", unit: "ก้อน", base: 12, spec: "6.5×15×3 ซม. · เผาเตาฟืน", specEn: "6.5×15×3 cm · wood-fired", cert: "—", lead: "14 วัน", wty: "—", moq: "1,000 ก้อน", note: "สีแต่ละล็อตต่างกันเล็กน้อย คือเสน่ห์ของงานมือ", noteEn: "Slight lot variation — handmade charm", colors: [["ส้มอิฐ", "#B0512F"], ["แดงเข้ม", "#8A3A24"], ["ส้มอ่อนไฟอ่อน", "#C87A50"]], sizes: ["มาตรฐาน", "จัมโบ้ 7×16×4"] },
  { cat: 4, brand: "BlockCraft", seller: "BlockCraft", model: "Breeze", th: "บล็อกช่องลมคอนกรีต", en: "Concrete breeze block", unit: "ก้อน", base: 65, spec: "19×19×9 ซม. · รับแรง 2.5 MPa", specEn: "19×19×9 · 2.5 MPa", cert: "มอก. 58", lead: "10 วัน", wty: "—", moq: "200 ก้อน", note: "มีลาย 6 แบบ สั่งผสมลายได้", noteEn: "6 patterns, mixable", colors: [["เทาซีเมนต์", "#A8A8A4"], ["ขาว", "#DCDCD8"]], sizes: ["19×19 ซม."] },
  { cat: 5, brand: "BoardTech", seller: "BoardTech", model: "FiberPlank", th: "แผ่นไฟเบอร์ซีเมนต์", en: "Fiber cement board", unit: "ตร.ม.", base: 385, spec: "กันชื้น · ทนไฟ 2 ชม.", specEn: "Moisture-proof · 2 h fire", cert: "มอก. 1427", lead: "5 วัน", wty: "10 ปี", moq: "10 แผ่น", note: "ใช้ได้ทั้งผนัง ฝ้า และพื้นยกเบา", noteEn: "Walls, ceilings, raised floors", colors: [["เทาซีเมนต์เปลือย", "#B8B5AC"], ["ขาวรองพื้น", "#D8D6D0"]], sizes: ["8 มม.", "12 มม.", "16 มม."] },
  { cat: 5, brand: "SCG", seller: "SCG Living", model: "Smartboard", th: "สมาร์ทบอร์ด", en: "Smartboard", unit: "แผ่น", base: 320, spec: "ขอบเรียบ · ไม่มีใยหิน", specEn: "Square edge · asbestos-free", cert: "มอก. 1427", lead: "3 วัน", wty: "10 ปี", moq: "10 แผ่น", note: "รอยต่อใช้ PU sealant ตามคู่มือ", noteEn: "PU sealant joints per manual", colors: [["เทา", "#B4B2AC"]], sizes: ["120×240 ซม. 8 มม.", "120×240 ซม. 10 มม."] },
  { cat: 6, brand: "Acoustic Pro", seller: "Acoustic Pro", model: "Perfo", th: "ยิปซัมอะคูสติกเจาะรู", en: "Perforated acoustic gypsum", unit: "ตร.ม.", base: 460, spec: "NRC 0.70 · ขอบ Tegular", specEn: "NRC 0.70 · Tegular", cert: "มอก. 219", lead: "10 วัน", wty: "5 ปี", moq: "20 ตร.ม.", note: "ต้องเว้น plenum ≥200 มม. เพื่อค่า NRC ตามสเปก", noteEn: "≥200 mm plenum for rated NRC", colors: [["ขาว", "#E9E7E0"]], sizes: ["รูกลม 8 มม.", "รูเหลี่ยม 12 มม."] },
  { cat: 6, brand: "Knauf", seller: "Knauf TH", model: "MoistShield", th: "ยิปซัมกันชื้น", en: "Moisture-resistant gypsum", unit: "แผ่น", base: 260, spec: "แกนกันชื้นสีเขียว · 9 มม.", specEn: "Green MR core · 9 mm", cert: "มอก. 219", lead: "3 วัน", wty: "5 ปี", moq: "20 แผ่น", note: "ห้องน้ำโซนเปียกควรกรุกระเบื้องทับ", noteEn: "Tile over in wet zones", colors: [["เขียว MR", "#B8C8B0"]], sizes: ["120×240 ซม."] },
  { cat: 7, brand: "Metro Steel", seller: "Metro Steel Supply", model: "H-Beam SS400", th: "เหล็ก H-Beam", en: "H-Beam", unit: "กก.", base: 24.5, spec: "Yield 245 MPa · JIS G3101", specEn: "Yield 245 MPa · JIS G3101", cert: "มอก. 1227", lead: "7 วัน", wty: "—", moq: "1 ตัน", note: "ราคาอิงตลาดรายสัปดาห์ ยืนราคา 7 วัน", noteEn: "Weekly market price, 7-day validity", colors: [["เหล็กดิบ", "#5B6670"]], sizes: ["150×150", "200×200", "300×300"] },
  { cat: 7, brand: "AlumTech", seller: "AlumTech", model: "Facade Fin", th: "ครีบอะลูมิเนียม", en: "Aluminium fin", unit: "ม.", base: 850, spec: "เคลือบ PVDF · กันซีดจาง 20 ปี", specEn: "PVDF coated · 20-yr fade", cert: "AAMA 2605", lead: "25 วัน", wty: "20 ปี", moq: "100 ม.", note: "สั่งสี RAL พิเศษได้ ขั้นต่ำ 300 ม.", noteEn: "Custom RAL from 300 m", colors: [["เงินอโนไดซ์", "#B8BEC4"], ["ดำด้าน", "#3A3C40"], ["ทองแชมเปญ", "#C0A878"]], sizes: ["50×150 มม.", "50×200 มม."] },
  { cat: 8, brand: "ClearView", seller: "ClearView Glass", model: "Low-E Lam", th: "กระจกลามิเนต Low-E", en: "Low-E laminated", unit: "ตร.ม.", base: 3200, spec: "SHGC 0.28 · VLT 62% · PVB 0.76", specEn: "SHGC 0.28 · VLT 62%", cert: "มอก. 1222", lead: "45 วัน", wty: "10 ปี", moq: "10 ตร.ม.", note: "แจ้งขนาดจริงหน้างานก่อนสั่งตัด", noteEn: "Confirm site dims before cutting", colors: [["ใสเขียวอ่อน", "#9FBCC4"], ["ใสน้ำเงิน", "#8AAEC4"]], sizes: ["6+6 มม.", "8+8 มม."] },
  { cat: 8, brand: "GlassArt", seller: "GlassArt BKK", model: "Fluted", th: "กระจกลอนฟลูท", en: "Fluted glass", unit: "ตร.ม.", base: 1850, spec: "หนา 8 มม. · เทมเปอร์", specEn: "8 mm tempered", cert: "มอก. 965", lead: "18 วัน", wty: "5 ปี", moq: "5 ตร.ม.", note: "ลอนแนวตั้งพรางสายตาแต่ผ่านแสง", noteEn: "Vertical flutes: privacy + light", colors: [["ใส", "#C8D8DC"], ["ชาอ่อน", "#B8A890"]], sizes: ["ลอน 10 มม.", "ลอน 20 มม."] },
  { cat: 9, brand: "CoolCoat", seller: "CoolCoat Thailand", model: "SolarShield", th: "สีสะท้อนความร้อน", en: "Heat-reflective paint", unit: "ถัง 9 ล.", base: 2450, spec: "SRI 108 · VOC <50 g/L", specEn: "SRI 108 · VOC <50", cert: "ฉลากเขียว", lead: "3 วัน", wty: "10 ปี", moq: "1 ถัง", note: "ทา 2 เที่ยว เว้น 4 ชม. ค่า SRI ถึงสเปก", noteEn: "2 coats, 4 h apart for rated SRI", colors: [["ขาวออฟไวท์", "#EDEBE6"], ["เทาอ่อน", "#CCCCC8"], ["ครีม", "#E4DCC8"]], sizes: ["9 ล.", "18.9 ล."] },
  { cat: 9, brand: "ColorLab", seller: "ColorLab Paint", model: "LimeWash", th: "สีปูนไลม์วอช", en: "Limewash", unit: "ถัง 5 ล.", base: 1650, spec: "ผิวด้านมีมิติ · ระบายไอน้ำ", specEn: "Matte texture · breathable", cert: "—", lead: "7 วัน", wty: "5 ปี", moq: "1 ถัง", note: "ต้องทารองพื้นแร่ก่อนเสมอ", noteEn: "Mineral primer required", colors: [["ขาวปูน", "#E8E4DC"], ["เทาหมอก", "#C4C2BC"], ["ดินเผา", "#C89078"], ["เขียวโคลน", "#A8AC94"]], sizes: ["5 ล."] },
  { cat: 10, brand: "GreenBuild", seller: "GreenBuild Insulation", model: "RockVolc", th: "ฉนวนใยหินภูเขาไฟ", en: "Rockwool", unit: "ตร.ม.", base: 185, spec: "60 kg/m³ · ไม่ลามไฟ A1 · NRC 0.90", specEn: "60 kg/m³ · A1 · NRC 0.90", cert: "ASTM C612", lead: "10 วัน", wty: "—", moq: "50 ตร.ม.", note: "ติดตั้งสวมถุงมือ ใยอาจระคายผิว", noteEn: "Wear gloves when installing", colors: [["เขียวขี้ม้า", "#8B8F72"]], sizes: ["50 มม.", "75 มม.", "100 มม."] },
  { cat: 10, brand: "ThermoSafe", seller: "ThermoSafe", model: "PE Foil", th: "ฉนวน PE สะท้อนรังสี", en: "PE reflective foil", unit: "ม้วน", base: 1250, spec: "หนา 5 มม. · ฟอยล์ 2 หน้า", specEn: "5 mm · double foil", cert: "—", lead: "3 วัน", wty: "10 ปี", moq: "1 ม้วน", note: "เว้นช่องอากาศ 25 มม. เพื่อประสิทธิภาพสูงสุด", noteEn: "25 mm air gap for best result", colors: [["ฟอยล์เงิน", "#C8CCD0"]], sizes: ["ม้วน 60 ตร.ม."] },
  { cat: 11, brand: "Fabrica", seller: "Fabrica TH", model: "Crib 5", th: "ผ้าบุกันน้ำกันไฟ", en: "FR waterproof fabric", unit: "ม.", base: 780, spec: "Martindale 60,000 · BS5852", specEn: "Martindale 60k · BS5852", cert: "—", lead: "18 วัน", wty: "—", moq: "10 ม.", note: "หน้ากว้าง 140 ซม. เผื่อลาย 10%", noteEn: "140 cm width, +10% pattern", colors: [["ชมพูตุ่น", "#B98A94"], ["เทาเข้ม", "#787880"], ["เขียวขวด", "#5A7868"], ["ครีม", "#D8CCB8"]], sizes: ["140 ซม."] },
  { cat: 11, brand: "Upholstery", seller: "Upholstery House", model: "MicroLeather", th: "หนังไมโครไฟเบอร์", en: "Microfiber leather", unit: "ม.", base: 1150, spec: "ทนขีดข่วน · เช็ดล้างได้", specEn: "Scratch-proof · wipeable", cert: "—", lead: "12 วัน", wty: "3 ปี", moq: "5 ม.", note: "เหมาะงาน hospitality ใช้งานหนัก", noteEn: "For heavy hospitality use", colors: [["น้ำตาลคาราเมล", "#9A6A48"], ["ดำ", "#3A3A3C"], ["เทาอุ่น", "#8A847C"]], sizes: ["137 ซม."] },
  { cat: 12, brand: "AquaFit", seller: "AquaFit", model: "EcoFlow", th: "ก๊อกอ่างประหยัดน้ำ", en: "Water-saving faucet", unit: "ชุด", base: 2890, spec: "4.5 ล./นาที · Chrome", specEn: "4.5 L/min · chrome", cert: "ฉลากประหยัดน้ำ", lead: "7 วัน", wty: "5 ปี", moq: "1 ชุด", note: "มีวาล์วเซรามิกกันหยด", noteEn: "Ceramic drip-free valve", colors: [["โครเมียม", "#A9B4BC"], ["ดำด้าน", "#4A4C50"], ["ทองแชมเปญ", "#C0A878"]], sizes: ["ก้านสั้น", "ก้านสูง"] },
  { cat: 12, brand: "BathPro", seller: "BathPro Studio", model: "RainSet", th: "ชุดฝักบัวเรนชาวเวอร์", en: "Rain shower set", unit: "ชุด", base: 6890, spec: "หัว 250 มม. · แรงดันต่ำใช้ได้", specEn: "250 mm head · low-pressure OK", cert: "—", lead: "10 วัน", wty: "5 ปี", moq: "1 ชุด", note: "แถมวาล์วกันน้ำร้อนลวก", noteEn: "Anti-scald valve included", colors: [["โครเมียม", "#AAB4BC"], ["นิกเกิลด้าน", "#9A9C98"]], sizes: ["ฝังผนัง", "ลอยผนัง"] },
  { cat: 13, brand: "Lumina", seller: "Lumina Lighting", model: "TrackPro", th: "ราง Magnetic Track", en: "Magnetic track", unit: "ชุด/ม.", base: 1850, spec: "48V · CRI 90 · Dim to warm", specEn: "48V · CRI 90 · DTW", cert: "มอก. 1955", lead: "14 วัน", wty: "3 ปี", moq: "3 ม.", note: "หัวโคมถอดสลับได้โดยไม่ตัดไฟ", noteEn: "Hot-swappable heads", colors: [["ดำ", "#38383A"], ["ขาว", "#E4E4E2"]], sizes: ["ฝังฝ้า", "ลอยฝ้า"] },
  { cat: 13, brand: "BrightWorks", seller: "BrightWorks", model: "LinearSlim", th: "โคมไฟเส้น LED", en: "LED linear", unit: "ม.", base: 950, spec: "CRI 90 · 3000K/4000K · IP44", specEn: "CRI 90 · IP44", cert: "มอก. 1955", lead: "7 วัน", wty: "3 ปี", moq: "5 ม.", note: "ตัดความยาวตามแบบได้ทุก 50 มม.", noteEn: "Cut-to-length per 50 mm", colors: [["อลูมิเนียม", "#B0B4B8"], ["ดำ", "#3C3C3E"]], sizes: ["กว้าง 20 มม.", "กว้าง 35 มม."] },
];
